import {
  DeleteObjectCommand,
  GetObjectCommand,
  HeadObjectCommand,
  PutObjectCommand,
  S3Client,
} from "@aws-sdk/client-s3";
import { createWriteStream } from "node:fs";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";

function getOptional(name: string) {
  return process.env[name]?.trim() || "";
}

function withFallback(name: string, fallback: string) {
  const value = process.env[name]?.trim();
  return value || fallback;
}

export function getS3Config() {
  const endpoint = withFallback("S3_ENDPOINT", "http://127.0.0.1:9000");
  const region = getOptional("S3_REGION") || "us-east-1";
  const bucket = withFallback("S3_BUCKET", "anime-videos");
  const accessKey = withFallback("S3_ACCESS_KEY", "minioadmin");
  const secretKey = withFallback("S3_SECRET_KEY", "minioadmin");
  const publicBaseUrl =
    getOptional("S3_PUBLIC_BASE_URL") || `${endpoint.replace(/\/+$/, "")}/${bucket}`;

  return { endpoint, region, bucket, accessKey, secretKey, publicBaseUrl };
}

export function getS3ConfigErrorMessage(err: unknown) {
  if (err instanceof Error) return err.message;
  return "S3 config error";
}

export function validateS3Config() {
  const cfg = getS3Config();
  if (!/^https?:\/\//i.test(cfg.endpoint)) {
    throw new Error("S3_ENDPOINT must start with http:// or https://");
  }
  if (!/^https?:\/\//i.test(cfg.publicBaseUrl)) {
    throw new Error("S3_PUBLIC_BASE_URL must start with http:// or https://");
  }
  return cfg;
}

export function getS3Bucket() {
  return validateS3Config().bucket;
}

export function getPublicS3BaseUrl() {
  return validateS3Config().publicBaseUrl.replace(/\/+$/, "");
}

export function buildPublicS3Url(objectKey: string) {
  const key = objectKey.replace(/^\/+/, "");
  return `${getPublicS3BaseUrl()}/${key}`;
}

function toProxyPathFromObjectKey(objectKey: string) {
  const key = objectKey
    .replace(/^\/+/, "")
    .split("/")
    .map((part) => encodeURIComponent(part))
    .join("/");
  return `/api/s3/${key}`;
}

function isLocalHostName(hostname: string) {
  const h = hostname.toLowerCase();
  return h === "localhost" || h === "127.0.0.1" || h === "::1";
}

function tryExtractObjectKeyFromUrl(rawUrl: string) {
  try {
    const u = new URL(rawUrl);
    if (!isLocalHostName(u.hostname)) return null;
    const bucket = getS3Bucket();
    const path = u.pathname.replace(/^\/+/, "");
    if (path.startsWith(`${bucket}/`)) {
      return path.slice(bucket.length + 1);
    }
    return path || null;
  } catch {
    return null;
  }
}

export function extractObjectKeyFromS3Url(rawUrl: string | null | undefined) {
  if (!rawUrl) return null;
  const trimmed = rawUrl.trim();
  if (!trimmed) return null;

  // Local proxy URL used in dev: /api/s3/<encoded object key>
  if (trimmed.startsWith("/api/s3/")) {
    const encoded = trimmed.slice("/api/s3/".length);
    if (!encoded) return null;
    return encoded
      .split("/")
      .map((part) => {
        try {
          return decodeURIComponent(part);
        } catch {
          return part;
        }
      })
      .join("/");
  }

  // Public URL generated by current config.
  const publicBase = getPublicS3BaseUrl();
  if (trimmed.startsWith(`${publicBase}/`)) {
    return trimmed.slice(publicBase.length + 1);
  }

  // Fallback for localhost/minio URLs.
  return tryExtractObjectKeyFromUrl(trimmed);
}

export function buildClientS3Url(objectKey: string) {
  const publicBase = getPublicS3BaseUrl();
  try {
    const baseUrl = new URL(publicBase);
    if (isLocalHostName(baseUrl.hostname)) {
      return toProxyPathFromObjectKey(objectKey);
    }
  } catch {
    return toProxyPathFromObjectKey(objectKey);
  }
  return buildPublicS3Url(objectKey);
}

export function resolveClientAssetUrl(rawUrl: string | null | undefined) {
  if (!rawUrl) return null;
  const key = tryExtractObjectKeyFromUrl(rawUrl);
  if (key) return toProxyPathFromObjectKey(key);
  return rawUrl;
}

export function getS3Client() {
  const cfg = validateS3Config();
  return new S3Client({
    region: cfg.region,
    endpoint: cfg.endpoint,
    forcePathStyle: true,
    credentials: {
      accessKeyId: cfg.accessKey,
      secretAccessKey: cfg.secretKey,
    },
  });
}

export async function s3ObjectExists(objectKey: string) {
  const key = objectKey.trim().replace(/^\/+/, "");
  if (!key) return false;

  const client = getS3Client();
  const bucket = getS3Bucket();
  try {
    await client.send(new HeadObjectCommand({ Bucket: bucket, Key: key }));
    return true;
  } catch {
    return false;
  }
}

async function bodyToBuffer(body: unknown) {
  if (!body) return Buffer.alloc(0);
  if (Buffer.isBuffer(body)) return body;
  if (body instanceof Uint8Array) return Buffer.from(body);
  if (body instanceof Readable) {
    const chunks: Buffer[] = [];
    for await (const chunk of body) {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
    }
    return Buffer.concat(chunks);
  }
  if (typeof (body as { transformToByteArray?: () => Promise<Uint8Array> }).transformToByteArray === "function") {
    const bytes = await (body as { transformToByteArray: () => Promise<Uint8Array> }).transformToByteArray();
    return Buffer.from(bytes);
  }
  return Buffer.alloc(0);
}

export async function downloadS3Object(objectKey: string) {
  const key = objectKey.trim().replace(/^\/+/, "");
  const client = getS3Client();
  const bucket = getS3Bucket();
  const res = await client.send(new GetObjectCommand({ Bucket: bucket, Key: key }));
  return bodyToBuffer(res.Body);
}

export async function downloadS3ObjectToFile(objectKey: string, destPath: string) {
  const key = objectKey.trim().replace(/^\/+/, "");
  const client = getS3Client();
  const bucket = getS3Bucket();
  const res = await client.send(new GetObjectCommand({ Bucket: bucket, Key: key }));

  if (!res.Body) {
    throw new Error("S3 object body is empty");
  }

  const body = res.Body;
  if (body instanceof Readable) {
    await pipeline(body, createWriteStream(destPath));
    return;
  }

  const buffer = await bodyToBuffer(body);
  if (!buffer.length) {
    throw new Error("S3 object body is empty");
  }
  const { writeFile } = await import("node:fs/promises");
  await writeFile(destPath, buffer);
}

export async function uploadS3Object(params: {
  objectKey: string;
  body: Buffer;
  contentType?: string;
}) {
  const key = params.objectKey.trim().replace(/^\/+/, "");
  const client = getS3Client();
  const bucket = getS3Bucket();
  await client.send(
    new PutObjectCommand({
      Bucket: bucket,
      Key: key,
      Body: params.body,
      ContentType: params.contentType ?? "video/mp4",
    })
  );
}

export async function deleteS3Object(objectKey: string) {
  const key = objectKey.trim().replace(/^\/+/, "");
  if (!key) return;

  const client = getS3Client();
  const bucket = getS3Bucket();
  await client.send(
    new DeleteObjectCommand({
      Bucket: bucket,
      Key: key,
    })
  );
}

export function getS3DebugConfigForLogs() {
  const cfg = validateS3Config();
  return {
    endpoint: cfg.endpoint,
    region: cfg.region,
    bucket: cfg.bucket,
    publicBaseUrl: cfg.publicBaseUrl,
  };
}
